### ISSUE TITLE
FTP server not available

### ISSUE THREAD

**Issue by annahyan** [bharris12/hsc_paper#1]
Hi, 
I can't access the FTP server. When using curl to download the datasets, I'm getting a:
`curl: (56) response reading failed` 
And using the FTP command also fails with:
`421 Service not available, remote server has closed connection`
Could you please recheck it or let me know if there's anything morecheckre I can do.
Best

**Comment by jhover** [comment]
Is this the data at: https://labshare.cshl.edu/shares/gillislab/resource/HSC_atlas/ 
If not, can you give the URL that should be working?

**Comment by annahyan** [comment]
Some of the files are the same, yes, but not all. 
The URL in the github [notebook](https://github.com/bharris12/hsc_paper/blob/main/notebooks/scNym_integration.ipynb) and in the preprint is: ftp://gillisdata.cshl.edu/data/HSC_atlas/

**Comment by jhover** [comment]
OK. The exact data that was at the ftp URL is now at both:
https://labshare.cshl.edu/shares/gillislab/papers/HSC_atlas/
https://gillisdata.cshl.edu/data/HSC_atlas/

The lab objects to running an FTP server on that host, but it can be accessed via HTTP.

**Comment by annahyan** [comment]
Great, thanks!
