### ISSUE TITLE
umap coordinates in processed_droplet_obs_data?

### ISSUE THREAD

**Issue by waltno** [bharris12/hsc_paper#2]
Not an actual issue with your code, but by any chance you could you add umap coordinates to your metadata file processed_droplet_obs_data.csv? I am currently re-making the Fig 2 object to have colnames and row names in Seurat, the icing on the cake would be to have the same UMAP coordinates :)

**Comment by bharris12** [comment]
I'm not at CSHL anymore so it isn't easy for me to modify the files hosted on the server but if you download `mouse_hsc_labeled.h5ad` and follow the code below I you can load in the coordinates easily, without having to load in the all the gene expression data. You just need the library rhdf5 installed

```
library(rhdf5)
h5<-H5Fopen('mouse_hsc_labeled.h5ad')
coords <- t(as.matrix(h5$obsm$X_umap))
cell_names <- h5$obs$`_index`
rownames(coords) <- cell_names
```

Hope this is helpful. If that doesn't work for you I can work with a colleague still there to modify the files

**Comment by waltno** [comment]
Hi! Thanks for getting back to me so quickly. I am a little confused by how things are set up. 

I want this object with gene names, cell barcodes, umap coordinates
<img width="778" alt="image" src="https://user-images.githubusercontent.com/94873838/196247920-a18c8d46-640d-40be-ab8c-dda6007005d7.png">

I got this object from the procesed_droplet.loom file but it does not contain and vars or obs names, so I cannot match the umap coordinates to the cell annotations in processed_droplet_obs_data.csv. The mouse_hsc_labeled.h5ad does not have the same scNym annotations nor the same umap coordinates as figure 2//i only get hematopoietic precursor cell and this embedding 

<img width="683" alt="image" src="https://user-images.githubusercontent.com/94873838/196248776-7d8d5d9e-36d6-4472-ba07-e59596dc1ba0.png">

**Comment by bharris12** [comment]
Sorry I haven't worked with this data in a while, but I just uploaded to the data folder in this repository the coordinates and confirmed that it matches Figure 2 
![image](https://user-images.githubusercontent.com/12770143/196519263-13e83ff7-c691-4e7f-99e8-d3a2299812bd.png)
